server:
  port: 6060
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_requirements?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: tyh
    password: TYHmysql25!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      add-mappings: true

app:
  jwt:
    secret: "change-this-to-a-long-random-secret-please"
    expireHours: 8
  upload-dir: ./data/uploads
  allow-origins: http://localhost:5173,http://localhost:6060,http://10.99.99.20,http://10.99.99.20:6060,http://10.99.99.20:1010

logging:
  level:
    org.springframework.security: INFO
    com.hospital.req: DEBUG

sms:
  url: "http://172.16.30.37:8899/api/sms/send"
  spCode: "100001"
  loginName: "9h_xxwyj"
  apiKey: "9b977a85510f120097f84a9f107a2748"
  templateId: "1100000022228"

